model = "gpt-5.6-sol"
model_reasoning_effort = "high"
personality = "pragmatic"
suppress_unstable_features_warning = true
web_search = "live"
approval_policy = "on-request"
sandbox_mode = "workspace-write"
notify = [
    "/Users/cj/.codex/computer-use/Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient",
    "turn-ended",
]
service_tier = "default"

[sandbox_workspace_write]
network_access = true

[projects."/Users/cj/code"]
trust_level = "trusted"

[projects."/Users/cj/code/placetide"]
trust_level = "trusted"

[projects."/Users/cj/code/brickanta"]
trust_level = "trusted"



[projects."/Users/cj/code/brickanta-workspace/brickanta"]
trust_level = "trusted"


[projects."/Users/cj/code/brickanta-root/brickanta"]
trust_level = "trusted"

[features]
unified_exec = true
shell_snapshot = true
collaboration_modes = true
steer = true
multi_agent = true
js_repl = false
memories = true

[notice]
hide_rate_limit_model_nudge = true

[[skills.config]]
path = "/Users/cj/.codex/skills/brainstorming/SKILL.md"
enabled = false

[[skills.config]]
path = "/Users/cj/.codex/skills/executing-plans/SKILL.md"
enabled = false

[[skills.config]]
path = "/Users/cj/.codex/skills/dispatching-parallel-agents/SKILL.md"
enabled = false

[[skills.config]]
path = "/Users/cj/.codex/skills/verification-before-completion/SKILL.md"
enabled = false

[[skills.config]]
path = "/Users/cj/.codex/skills/writing-plans/SKILL.md"
enabled = false

[[skills.config]]
path = "/Users/cj/.codex/skills/writing-skills/SKILL.md"
enabled = false

[[skills.config]]
path = "/Users/cj/.agents/skills/zoom-out/SKILL.md"
enabled = false

[[skills.config]]
path = "/Users/cj/.agents/skills/diagnose/SKILL.md"
enabled = false

[[skills.config]]
path = "/Users/cj/.agents/skills/design-an-interface/SKILL.md"
enabled = false

[[skills.config]]
path = "/Users/cj/.agents/skills/find-skills/SKILL.md"
enabled = false

[[skills.config]]
path = "/Users/cj/.agents/skills/teach/SKILL.md"
enabled = false

[[skills.config]]
path = "/Users/cj/.agents/skills/request-refactor-plan/SKILL.md"
enabled = false

[mcp_servers.linear]
url = "https://mcp.linear.app/mcp"
enabled = false

[mcp_servers.playwright]
command = "npx"
args = ["@playwright/mcp@latest"]
enabled = false

[mcp_servers.posthog]
url = "https://mcp.posthog.com/mcp"
bearer_token_env_var = "MCP_BEARER_TOKEN"
enabled = false

[mcp_servers.inngest-dev]
url = "http://localhost:8288/mcp"
enabled = false

[mcp_servers.chrome-devtools]
command = "npx"
args = ["chrome-devtools-mcp@latest"]

[mcp_servers.chrome-devtools.tools.fill]
approval_mode = "approve"

[mcp_servers.chrome-devtools.tools.take_snapshot]
approval_mode = "approve"

[mcp_servers.chrome-devtools.tools.press_key]
approval_mode = "approve"

[mcp_servers.chrome-devtools.tools.fill_form]
approval_mode = "approve"

[mcp_servers.chrome-devtools.tools.new_page]
approval_mode = "approve"

[mcp_servers.chrome-devtools.tools.take_screenshot]
approval_mode = "approve"

[mcp_servers.node_repl]
args = []
command = "/Applications/ChatGPT.app/Contents/Resources/cua_node/bin/node_repl"
startup_timeout_sec = 120

[mcp_servers.node_repl.env]
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = "/Applications/ChatGPT.app/Contents/Resources/cua_node/lib/node_modules"
NODE_REPL_NODE_PATH = "/Applications/ChatGPT.app/Contents/Resources/cua_node/bin/node"
NODE_REPL_TRUSTED_CODE_PATHS = "/Users/cj/.codex"
CODEX_HOME = "/Users/cj/.codex"
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "14e425736668bf21b5b39f2cc022ee8684728617fb5c49f35533c2e349f47193,6d25aa7656feac858f3a3bdaea5bcbab0dbfd426c9de8e6931ce90c399ee8e4f"
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = "Control the in-app browser in conjunction with the Browser Plugin."
NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = "Control the Chrome browser in conjunction with the Chrome Plugin. Prefer this method of controlling Chrome over alternatives (such as Computer Use) unless the user explicitly mentions an alternative."
NODE_REPL_INSTRUCTIONS_USE_CASE_COMPUTER_USE = "Control desktop apps on macOS through Computer Use."
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
BROWSER_USE_CODEX_APP_VERSION = "26.721.81911"
CODEX_CLI_PATH = "/Applications/ChatGPT.app/Contents/Resources/codex"

[mcp_servers.excalidraw]
command = "node"
args = [
    "/Users/cj/Library/Application Support/Claude/Claude Extensions/local.mcpb.anton-pidkuiko.excalidraw-mcp-app/dist/index.js",
    "--stdio",
]
enabled = false

[mcp_servers.langsmith]
url = "https://eu.api.smith.langchain.com/mcp"
enabled = false

[mcp_servers.computer-use]
command = "./Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient"
args = ["mcp"]
cwd = "."
enabled = false

[mcp_servers.brickanta-wiki-remote]
url = "http://localhost:9080/mcp"

[plugins."github@openai-curated"]
enabled = true

[plugins."linear@openai-curated"]
enabled = false

[plugins."linear@openai-curated-remote"]
enabled = false

[plugins."convex@openai-curated-remote"]
enabled = false

[plugins."cloudflare@openai-curated"]
enabled = false

[plugins."cloudflare@openai-curated-remote"]
enabled = false

[plugins."build-web-apps@openai-curated"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."circleback@openai-curated"]
enabled = true

[plugins."posthog@claude-plugins-official"]
enabled = false

[plugins."pdf@openai-primary-runtime"]
enabled = true

[plugins."workos@claude-plugins-official"]
enabled = false

[plugins."template-creator@openai-primary-runtime"]
enabled = false

[plugins."visualize@openai-bundled"]
enabled = true

[plugins."sites@openai-bundled"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[marketplaces.openai-bundled]
last_updated = "2026-07-30T10:40:59Z"
source_type = "local"
source = "/Users/cj/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.openai-primary-runtime]
last_updated = "2026-07-28T11:51:40Z"
source_type = "local"
source = "/Users/cj/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[desktop]
appearanceLightCodeThemeId = "one"
usePointerCursors = false
followUpQueueMode = "steer"
preventSleepWhileRunning = true
keepRemoteControlAwakeWhilePluggedIn = true
git-branch-prefix = "codex/"
git-create-pull-request-as-draft = false
git-pull-request-merge-method = "squash"
git-show-sidebar-pr-icons = true
git-pr-instructions = "always use conventional commit pattern for title, such as `fix:`, `chore:` `feat:` etc"
default-service-tier = "priority"
dock-icon-preference = "codex-system"
conversationDetailMode = "STEPS_COMMANDS"
show-context-window-usage = true
hotkey-window-projectless-default-enabled = true
appearanceTheme = "system"
enabled-reasoning-efforts = ["low", "medium", "high", "xhigh", "ultra", "max"]
avatar-overlay-mascot-width-px = 103
selected-avatar-id = "fireball"

[desktop.appearanceLightChromeTheme]
accent = "#526fff"
contrast = 45
ink = "#383a42"
opaqueWindows = true
surface = "#fafafa"

[desktop.appearanceLightChromeTheme.fonts]
ui = "Inter"

[desktop.appearanceLightChromeTheme.semanticColors]
diffAdded = "#3bba54"
diffRemoved = "#e45649"
skill = "#526fff"

[desktop.open-in-target-preferences]
global = "cursor"

[desktop.open-in-target-preferences.perPath]
"/Users/cj/code/placetide" = "cursor"

[tui.model_availability_nux]
"gpt-5.5" = 2

[hooks.state."posthog@claude-plugins-official:hooks/hooks.json:pre_tool_use:0:0"]
trusted_hash = "sha256:3dc55a922b47b9418381076dbfc51fbe2a5bdbe2f86469022c5df91eed9c5c52"

[shell_environment_policy.set]
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "14e425736668bf21b5b39f2cc022ee8684728617fb5c49f35533c2e349f47193,6d25aa7656feac858f3a3bdaea5bcbab0dbfd426c9de8e6931ce90c399ee8e4f"
NODE_REPL_TRUSTED_CODE_PATHS = "/Users/cj/.codex"

[memories]
generate_memories = true
use_memories = true
